# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e105929b02e431aad4b0298daec7eee568e87637099ba2b0a84ec9f522af1d5c076687ada8ae9e2440d49d61987c2e1a49936243172b9394fb931c81aef7fd

test:
  secret_key_base: 84c56e40f5ebc196402ba77f2405eb237191a6332e5559fcdbbbb9e355cd4f91a736750b68a2f6341051767076c68b06374c856182fc7e6b121e6b22b6e7ea61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
